"""Shared Katalog domain limits."""

from typing import Final

MAX_PLAYBACK_QUEUE_SIZE: Final[int] = 500
MAX_PLAYBACK_STATE_BATCH_SIZE: Final[int] = 500
PLAYBACK_SESSION_PROGRESS_GRACE_PERIOD_SECONDS: Final[float] = 30.0
MAX_SUBTITLE_TIMING_OFFSET_MILLISECONDS: Final[int] = 30_000
MAX_ARTWORK_PER_ITEM: Final[int] = 12
DEFAULT_MEDIA_TRANSFER_CHUNK_SIZE: Final[int] = 256 * 1024
MAX_MEDIA_TRANSFER_CHUNK_SIZE: Final[int] = 1024 * 1024
DEFAULT_MEDIA_TRANSFER_WORKER_COUNT: Final[int] = 4
DEFAULT_DATABASE_CONNECTION_POOL_SIZE: Final[int] = 8
