"""Supported client-facing contracts for Katalog's HTTP API.

Kanvas, Kestrel, Yukibot, and remote integrations import only from this module.
It intentionally contains no persistence, filesystem, or provider implementation.
"""

from kasana.katalog.api.contracts import (
    APIError,
    ArtworkFetchRequest,
    ArtworkKind,
    ArtworkSelection,
    Availability,
    BackgroundJob,
    CollectionSummary,
    ContinueWatchingEntry,
    HealthResponse,
    JobStatus,
    JobSubmission,
    LibraryItemDetail,
    LibraryItemKind,
    LibraryItemSummary,
    MediaStreamSummary,
    MediaTechnicalSummary,
    MetadataMatchRequest,
    MetadataRejectRequest,
    MetadataReviewCandidate,
    MutationResult,
    OnDeckEntry,
    OrderedPlayableEntry,
    PaginatedResponse,
    PlaybackStateResponse,
    ProgressUpdate,
    ScanRequest,
    StatusResponse,
    WatchedFilter,
    WatchOrderDetail,
    WatchOrderKind,
    WatchOrderSummary,
)
from kasana.katalog.client import (
    ArtworkContent,
    ConditionalItem,
    KatalogClient,
    KatalogClientError,
    KatalogClientErrorKind,
)

__all__ = [
    "APIError",
    "ArtworkContent",
    "ArtworkFetchRequest",
    "ArtworkKind",
    "ArtworkSelection",
    "Availability",
    "BackgroundJob",
    "CollectionSummary",
    "ConditionalItem",
    "ContinueWatchingEntry",
    "HealthResponse",
    "JobStatus",
    "JobSubmission",
    "KatalogClient",
    "KatalogClientError",
    "KatalogClientErrorKind",
    "LibraryItemDetail",
    "LibraryItemKind",
    "LibraryItemSummary",
    "MediaStreamSummary",
    "MediaTechnicalSummary",
    "MetadataMatchRequest",
    "MetadataRejectRequest",
    "MetadataReviewCandidate",
    "MutationResult",
    "OnDeckEntry",
    "OrderedPlayableEntry",
    "PaginatedResponse",
    "PlaybackStateResponse",
    "ProgressUpdate",
    "ScanRequest",
    "StatusResponse",
    "WatchOrderDetail",
    "WatchOrderKind",
    "WatchOrderSummary",
    "WatchedFilter",
]
